version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
     - "1883:1883"
     - "9001:9001"
    volumes:
     - /etc/mosquitto/conf:/mosquitto/config
     - /etc/mosquitto/data:/mosquitto/data
     - /etc/mosquitto/log:/mosquitto/log
  portainer:
    image: portainer/portainer
    ports:
     - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /etc/portainer_data:/data
